const GameAction = {
    MOVE_LEFT: "MOVE_LEFT",
    MOVE_UP: "MOVE_UP",
    MOVE_RIGHT: "MOVE_RIGHT",
    MOVE_DOWN: "MOVE_DOWN",

    ROTATE_LEFT: "ROTATE_LEFT",
    ROTATE_RIGHT: "ROTATE_RIGHT",

    PLACE_PIECE: "PLACE_PIECE",
    MAKE_PIECE: "MAKE_PIECE"
}
export default GameAction;